/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#9ecfd1",
        "secondary": "#6b5c4f",
        "error": "#ba1a1a",
        "secondary-fixed": "#f4dfce",
        "surface": "#f3faff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#1a4e50",
        "inverse-surface": "#123441",
        "tertiary": "#1c4f51",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#324e2a",
        "primary-fixed": "#caecbc",
        "surface-dim": "#bedfef",
        "primary-container": "#4a6741",
        "on-surface": "#001f29",
        "surface-tint": "#496640",
        "tertiary-container": "#366769",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#ccedfe",
        "on-primary-fixed": "#062104",
        "surface-container-highest": "#c6e8f8",
        "surface-bright": "#f3faff",
        "surface-container": "#d8f2ff",
        "on-tertiary-container": "#b1e3e5",
        "on-secondary-fixed-variant": "#524438",
        "on-surface-variant": "#434840",
        "tertiary-fixed": "#b9ecee",
        "background": "#f3faff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#c2e4b4",
        "primary-fixed-dim": "#afd0a1",
        "primary": "#334f2b",
        "secondary-container": "#f4dfce",
        "outline-variant": "#c3c8bd",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#dff4ff",
        "on-background": "#001f29",
        "on-tertiary-fixed": "#002021",
        "inverse-primary": "#afd0a1",
        "on-secondary-container": "#716154",
        "outline": "#73796f",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#24190f",
        "surface-variant": "#c6e8f8",
        "surface-container-low": "#e6f6ff",
        "secondary-fixed-dim": "#d7c3b3"
      },
      fontFamily: {
        "display": ["Fraunces", "Georgia", "serif"],
        "headline": ["Manrope", "sans-serif"],
        "body": ["\"IBM Plex Sans\"", "system-ui", "-apple-system", "sans-serif"],
        "label": ["\"IBM Plex Sans\"", "system-ui", "-apple-system", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
